language: node_js
node_js:
  - 12
cache: npm
branches:
  only:
    - hexo
script:
  - hexo clean
  - hexo generate
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: true
  on:
    branch: hexo
  local-dir: public
